### ISSUE TITLE
u want kernel source?

### ISSUE THREAD

**Issue by madhavsheth** [CipherOS/android_manifest#4]

**Comment by CyberJalagam** [comment]
@madhavsheth No

**Comment by kardebayan** [comment]
@madhavsheth Yes

**Comment by CyberJalagam** [comment]
@kardebayan Ok

**Comment by cArN4gEisDeD** [comment]
@madhavsheth Yes sir bro bhai, send for C2 wen rather than releasing 69 gay phones

**Comment by ElectroPerf** [comment]
@madhavsheth Yes, the new one.. which  realme claims that its not linux kernel

**Comment by ElectroPerf** [comment]
@madhavsheth

**Comment by techyminati** [comment]
@madhavsheth whoever you are, this repo isn't a joke & you're unfunny and cringe. Stop it if you cant fix basic header path errors, also realme R kernels are NOT broken at all. So Stop this nonsense. Thanks for understanding.
