### ISSUE TITLE
Error while building eleven

### ISSUE THREAD

**Issue by elrohir79** [CipherOS/android_manifest#5]
Hi there.
I'm building unofficial for matisse and millet (Samsung) and got an error while building for my monthly updates.
Maybe it's a broken ManagedProvisioning app.
Could you please have an eye on it?
Cheers
Martin

[error-building-log.txt](https://github.com/CipherOS/android_manifest/files/8933129/error-building-log.txt)

**Comment by techyminati** [comment]
Hi, unfortunately the Android 11 source is in stale/abandoned, but I can try to fix above error for now, When did you manage to compile Android 11 source last time?

**Comment by elrohir79** [comment]
My last working build was around 2022-05-15

**Comment by techyminati** [comment]
okay, let me check .

**Comment by techyminati** [comment]
* Try to dirty-sync again using ```repo sync --force-sync -j4``` command & let me know.

**Comment by elrohir79** [comment]
Ok, i'll start building. It will take a while, the error appears at 95% or later. 
I'll give you a ping as soon as it's done.
Thx

**Comment by elrohir79** [comment]
Problem is solved, building works fine again, ROM is booting.
Thank you for your help.

**Comment by techyminati** [comment]
with that the follow changes are also merged

* Bump Security String to June 2022
* Opensourced CipherOS R Exclusive UI/UX


Closed.
