### ISSUE TITLE
Error adding local_manifests in .repo

### ISSUE THREAD

**Issue by TienIC** [CipherOS/android_manifest#8]
root@x79g:~/rom# repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
warning: unable to access '/home/bean/.config/git/config': Permission denied
  File "/root/rom/.repo/repo/main.py", line 80
    file=sys.stderr,
        ^
SyntaxError: invalid syntax

**Comment by techyminati** [comment]
Fix your build env
